### ISSUE TITLE
[Media Attachments] Admins should be able to upload multiple media attachments for a Story

### ISSUE THREAD

**Issue by cmhnk** [rubyforgood/terrastories#11]
Right now we can only upload one media attachment per story in the admin dashboard. We will want to be able to upload multiple pieces of media since one Story can have a video, photos, audio clips, etc.

**Comment by mkmckenzie** [comment]
Multiple attachments is already supported in the app! After clicking the "upload files" button, hold down `shift` and select as many files as you need.
