### ISSUE TITLE
[Media Attachments] Admins should be able to delete media attachments on a Story

### ISSUE THREAD

**Issue by cmhnk** [rubyforgood/terrastories#12]
Currently media can't be deleted in Administrate because it's a field on Story. Let's add a button to the Story edit page on the administrate dashboard that can clear and delete media attachments (individually or all of them).

**Comment by mkmckenzie** [comment]
See: https://github.com/Dreamersoul/administrate-field-active_storage#removingdeleting-an-attachment

**Comment by s-nicas** [comment]
Feature added: https://github.com/rubyforgood/terrastories/pull/56
