### ISSUE TITLE
[i18n] Make it easier to add new languages

### ISSUE THREAD

**Issue by cmhnk** [rubyforgood/terrastories#13]
(This is a large ticket -- the first part of working on this should probably be coming up with a strategy)

In order to add a language to Terrastories, the code has to be modified in a number of places:

application.rb: line 21 (default locale)
routes.rb: line 12 (list of available languages)
welcome/index.html.erb: line 27 (the front page language picker)
config/locales: here, the user has to add the languages as defined in the above places.

We should make it easy enough that the user doesn't have to change any of the code, and document the process of adding new languages.

**Comment by rudokemper** [comment]
How does it work?

**Comment by albertchae** [comment]
The existing locale yaml files have been moved from `rails/config/locales` into their own directories e.g. `rails/config/locales/en`, `rails/config/locales/mat`. The code looks at those directories to determine available locales. If you want to add another language (like `pt`), create a new directory `rails/config/locales/pt` and put the corresponding yaml files inside. Once you restart the server, the new language option should show up on the homepage.

**Comment by rudokemper** [comment]
Perfect - thanks!
