### ISSUE TITLE
Alternative architecture for displaying video content in the cards

### ISSUE THREAD

**Issue by rudokemper** [rubyforgood/terrastories#140]
Now that we have a pipeline for importing data and with the Matawai project have ~300 stories in the CMS, the massive load of videos pre-loading at the same time is making the map view (and Administrate) extremely slow, resulting in a page Timeouts and eventually Rails crashing. We either need for the videos to not pre-load at all, or a different solution.

**Comment by lauramosher** [comment]
These are two options that come to mind right now:

1. As you suggest; we don't preload the videos and load them later to reduce page load.
2. We “infinite scroll” the Story List, so we only load a reasonable number at any given time, also reducing the load, but allowing the video content to be loaded immediately.
