### ISSUE TITLE
Add Speaker name to each Story in the list

### ISSUE THREAD

**Issue by mirandawang** [rubyforgood/terrastories#156]
In addition to displaying the Speaker photo, let's also display the Speaker names in each Story in the sidebar. The change should be in the React component somewhere around here :) https://github.com/rubyforgood/terrastories/blob/master/rails/app/javascript/components/StoryList.jsx#L65

**Comment by MxOliver** [comment]
I'd like to work on this issue!

**Comment by mirandawang** [comment]
Closed by #188 - thanks Ali!
