### ISSUE TITLE
[CSV Data Importer] Resolve timeout issue and check for duplicates

### ISSUE THREAD

**Issue by rudokemper** [rubyforgood/terrastories#16]
Currently, the CSV importer may time out over some time when processing a large amount of video content. When you then try to run the CSV importer again, it uploads the same content all over again, resulting in duplicates.

The CSV importer should check for duplicates, and the timeout issue should be resolved somehow.

**Comment by baweaver** [comment]
This seems to be two distinct issues:

1. Prevent duplicate records, which I believe #20 achieves
2. Find out why the video uploads are clocking out
