### ISSUE TITLE
Internationalization and Localization

### ISSUE THREAD

**Issue by Bootjack** [rubyforgood/terrastories#29]
The native language of the people of Suriname is Matawai, which none of us speak. Well, Rudo does.

Add support for localization so that we can build the app in English and someone (Rudo) can translate phrases in our app to Matawai.

Add support for switching locales, probably with support for routes beginning with `/en/` and `/srm/` to distinguish between the two. (It seems "srm" is the official language code for Saramaccan, of which Matawai is a dialect, I guess.)

http://guides.rubyonrails.org/i18n.html

**Comment by AliTopal89** [comment]
Look in to ways of building a language picker on the application home page to switch between available languages
