### ISSUE TITLE
[UI - Filters Bug] 

### ISSUE THREAD

**Issue by cmhnk** [rubyforgood/terrastories#48]
The solutions for issues #7 and #8 made it so that the markers on the map and the stories in the sidebar are always perfectly in sync.

However, the desired behavior is slightly different -- if a marker is clicked, we do want to filter the sidebar stories to show only stories corresponding to that point, but we _don't_ want clicking on that point to result in all the other markers disappearing.

**Comment by baweaver** [comment]
https://github.com/rubyforgood/terrastories/pull/51
