### ISSUE TITLE
[Migrations] Update models

### ISSUE THREAD

**Issue by cmhnk** [rubyforgood/terrastories#5]
Story model:
Let's update the Story model to match these fields:

title : String
desc : String
where_interviewed : Place (One to Many relationship)
date_interviewed : DateTime
interviewer : String
language : String
video : ActiveStorage Media attachment (Many to Many relationship)
permission_level : Enum

Remove Point model and capture its data in the Place model

Update the Point and Place models so they are combined in one model named Place. Let Place have these fields:

name : String (same as the Point model)
type : String
description : String (same as the Point model)
region : String
lat : float (same as the Point model)
long : float

**Comment by s-nicas** [comment]
> emove Point model and capture its data in the Place model
> 
> Update the Point and Place models so they are combined in one model named Place. Let Place have these fields:
> 
> name : String (same as the Point model)
> type : String
> description : String (same as the Point model)
> region : String
> lat : float (same as the Point model)
> long : float

**Comment by s-nicas** [comment]
Stories model updated https://github.com/rubyforgood/terrastories/pull/30
