### ISSUE TITLE
Add panning & zooming when you click on a point

### ISSUE THREAD

**Issue by mirandawang** [rubyforgood/terrastories#63]
When you click on a point, right now, it displays the marker and shows its stories in the card. 
But it would be great if the map panned & zoomed a bit up to that point when it's "active". 
Check out these links for more info:
https://www.mapbox.com/mapbox-gl-js/example/center-on-symbol/
https://www.mapbox.com/mapbox-gl-js/example/flyto/

**Comment by mdworken** [comment]
I've used mapbox-gl-js centering at work, want me to knock this one out too?

**Comment by mirandawang** [comment]
@mdworken That would be awesome! Please take on whichever issues you'd like to do! More help is always welcome :) For housekeeping reasons though please follow the steps in our CONTRIBUTING guidelines. Thanks again!!
