### ISSUE TITLE
Update the seed data

### ISSUE THREAD

**Issue by mirandawang** [rubyforgood/terrastories#65]
Let's update the seed data:
More data - speakers, points, stories
Connect them - which points have which stories
Incorporate videos into the stories
Incorporate photos with the speakers

**Comment by bperlik** [comment]
I this assigned? If not I'd like to work on it.

**Comment by mirandawang** [comment]
@bperlik This is currently not claimed by anyone! If you could work on it, that would be great! Thank you!
