### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mirandawang** [rubyforgood/terrastories#66]
We're test-less right now! Some unit tests would be nice.

**Comment by colinxfleming** [comment]
hey! I'm happy to take this on at least in part. I'll write up some basic model/low hanging fruit tests to start and then we can figure out what to do about something more involved if necessary.

**Comment by mirandawang** [comment]
@colinxfleming  Sounds great! Please take a look at our CONTRIBUTING.md guidelines for more details on the steps. Thanks so much!

**Comment by colinxfleming** [comment]
hey, sorry, my life got wildly overtaken by events and my free time thru the end of the year is pretty much shot. Not going to be able to swing this anymore. sorry!

**Comment by bperlik** [comment]
I'd like to work on this. I love writing tests!

**Comment by mirandawang** [comment]
Hi @bperlik , that would be really great if you could work on some unit tests for us! Thank you!
