### ISSUE TITLE
Update the introduction text "What is a Terrastory?"

### ISSUE THREAD

**Issue by Bootjack** [rubyforgood/terrastories#76]
Use the following text:

Terrastories are audiovisual recordings of place-based storytelling. This offline-compatible application enables local communities to locate and map their own oral storytelling traditions about places of significant meaning or value to them.

**Comment by bperlik** [comment]
I can do this.

**Comment by mirandawang** [comment]
@bperlik Here's the introduction text :) 
```Terrastories are audiovisual recordings of place-based storytelling. This offline-compatible application enables local communities to locate and map their own oral storytelling traditions about places of significant meaning or value to them.```
Thanks for claiming this issue!

**Comment by mirandawang** [comment]
@bperlik Sorry, I misread your message! The introduction text should go into the card partial, under "What's a terrastory?". Currently the placeholder is Lorem Ipsum. Thanks again!

**Comment by nickmjones** [comment]
Candidate to move into "MVP for Matawai" milestone?

**Comment by nickmjones** [comment]
Marking this closed. These changes should be in `master` now.

**Comment by mirandawang** [comment]
Reopening this issue since it seems to still be addressed in https://github.com/rubyforgood/terrastories/pull/79

**Comment by nickmjones** [comment]
Closed in #89
