### ISSUE TITLE
Change title from “App” to Terrastories: Matawai konde and use Terrastories favicon

### ISSUE THREAD

**Issue by mirandawang** [rubyforgood/terrastories#96]
Right now, the title of the webpage is just "App". Let's update it to say "Terrastories: Matawai konde" and use this favicon!

![image](https://user-images.githubusercontent.com/8590508/45177868-2d90f500-b1e2-11e8-9e0e-5dc0a46ead71.png)

**Comment by rudokemper** [comment]
I just took care of this one! Will submit a PR with both items fixed. @nickmjones @mirandawang
